/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemrograman.visual;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Aditya Maulana
 */
public final class NasabahPanel extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form nasabahPanel
     */
    protected void kosong() {
        Id.setText("");
        no_nasabah_baru.setText("");
        nama_nasabah_baru.setText("");
        kelas_nasabah_baru.setText("");
        alamat_nasabah_baru.setText("");
    }
    String id_siswa;
     public void datatable(){
        
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("No. Induk");
        tbl.addColumn("Nama");
        tbl.addColumn("Kelas");
        tbl.addColumn("Alamat");
        
        String sql = "SELECT * FROM siswa";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String id = hasil.getString("id");
                id_siswa = hasil.getString("id_siswa");
                String nama_siswa = hasil.getString("nama_siswa");
                String kelas = hasil.getString("kelas");
                String alamat = hasil.getString("alamat");
                
                String[] data = {id,id_siswa,nama_siswa,kelas,alamat};
                System.out.println(id_siswa);
                tbl.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
            
        }    
        jTable1.setModel(tbl);
        }
    
    public NasabahPanel() {
        initComponents();
        
        datatable();
        Id.setEnabled(false);
        saldoawal.setEnabled(false);
        saldoawal.setText("10.000");
        System.out.println(date.getTanggal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no_nasabah_baru = new javax.swing.JTextField();
        nama_nasabah_baru = new javax.swing.JTextField();
        kelas_nasabah_baru = new javax.swing.JTextField();
        alamat_nasabah_baru = new javax.swing.JTextField();
        input_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        saldoawal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("No. Induk Siswa :");

        jLabel2.setText("Nama Siswa :");

        jLabel3.setText("Kelas :");

        jLabel4.setText("Alamat Siswa :");

        no_nasabah_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_nasabah_baruActionPerformed(evt);
            }
        });

        alamat_nasabah_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat_nasabah_baruActionPerformed(evt);
            }
        });

        input_button.setText("Tambah");
        input_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Nasabah");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        jLabel7.setText("Saldo Awal :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(no_nasabah_baru)
                                    .addComponent(nama_nasabah_baru)
                                    .addComponent(kelas_nasabah_baru, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(alamat_nasabah_baru, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Id)
                                    .addComponent(saldoawal)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(input_button)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(no_nasabah_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama_nasabah_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kelas_nasabah_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(alamat_nasabah_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_button)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void input_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_buttonActionPerformed
        String no_induk = no_nasabah_baru.getText();
        String nama = nama_nasabah_baru.getText();
        String kelas = kelas_nasabah_baru.getText();
        String alamat = alamat_nasabah_baru.getText();
        //String saldo_awal = saldoawal.getText();
               
        try {
            com.mysql.jdbc.Statement st = (com.mysql.jdbc.Statement) conn.createStatement();
            st.executeUpdate("insert into siswa (id_siswa,nama_siswa,kelas,alamat,total_saldo,total_penarikan) VALUES ('"+ no_induk +"','"+ nama +"','"+ kelas +"','"+ alamat +"','"+10000+"','"+0+"')");
            st.executeUpdate("insert into simpanan (id_siswa,jumlah,tgl) VALUES ('"+no_induk+"','"+10000+"','"+date.getTanggal()+"')");
            st.executeUpdate("insert into penarikan (id_siswa,saldo,tgl) VALUES ('"+no_induk+"','0','"+date.getTanggal()+"')");
            st.close();
            JOptionPane.showMessageDialog(null, "Data Mahasiswa Berhasil Di Simpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Mahasiswa Gagal Di Simpan "  + e);
        }
        datatable();
        kosong();

    }//GEN-LAST:event_input_buttonActionPerformed

    private void no_nasabah_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_nasabah_baruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_nasabah_baruActionPerformed

    private void alamat_nasabah_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat_nasabah_baruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat_nasabah_baruActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String id = Id.getText();
        String no_induk = no_nasabah_baru.getText();
        String nama = nama_nasabah_baru.getText();
        String kelas = kelas_nasabah_baru.getText();
        String alamat = alamat_nasabah_baru.getText();

        try {
            com.mysql.jdbc.Statement st = (com.mysql.jdbc.Statement) conn.createStatement();
            st.executeUpdate("update siswa set id_siswa = '"+ no_induk +"',nama_siswa = '"+ nama +"', kelas = '"+ kelas +"', alamat = '"+ alamat +"' where id = '"+ id +"'");
            st.executeUpdate("update simpanan set id_siswa = '"+ no_induk +"' where id_siswa = '"+ id_siswa +"'");
            st.executeUpdate("update penarikan set id_siswa = '"+ no_induk +"' where id_siswa = '"+ id_siswa +"'");
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Di Edit"  + e);
        }
        datatable();
        kosong();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int bar = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(bar, 0).toString();
        String no_induk = jTable1.getValueAt(bar, 1).toString();
        String nama = jTable1.getValueAt(bar, 2).toString();
        String kelas = jTable1.getValueAt(bar, 3).toString();
        String alamat = jTable1.getValueAt(bar, 4).toString();

        Id.setText(id);
        no_nasabah_baru.setText(no_induk);
        nama_nasabah_baru.setText(nama);
        kelas_nasabah_baru.setText(kelas);
        alamat_nasabah_baru.setText(alamat);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String no_induk = no_nasabah_baru.getText();
        String id = Id.getText();
        try {
            com.mysql.jdbc.Statement st = (com.mysql.jdbc.Statement) conn.createStatement();
            st.executeUpdate("delete from siswa where id = '"+ id +"'");
            st.executeUpdate("delete from penarikan where id_siswa = '"+ no_induk +"'");
            st.executeUpdate("delete from simpanan where id_siswa = '"+ no_induk +"'");
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus" + e);
        }
        datatable();
        kosong();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTextField alamat_nasabah_baru;
    private javax.swing.JButton input_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kelas_nasabah_baru;
    private javax.swing.JTextField nama_nasabah_baru;
    private javax.swing.JTextField no_nasabah_baru;
    private javax.swing.JTextField saldoawal;
    // End of variables declaration//GEN-END:variables

    private static class DefaultTableMode extends DefaultTableModel {

        public DefaultTableMode(Object object, Object[] Baris) {
        }
    }
}
