/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemrograman.visual;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Aditya Maulana
 */
public class PenarikanPanel extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form SetoranPanel
     */
    public PenarikanPanel() {
        initComponents();
        datatable("");
        cari_nama.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                datatable(cari_nama.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                datatable(cari_nama.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    public void datatable(String cari_nama){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("No. Induk");
        tbl.addColumn("Nama");
        tbl.addColumn("Total Saldo");
        if (cari_nama.equals("")){
            try {
            Statement st = (Statement) conn.createStatement();
            ResultSet res = st.executeQuery("select id,id_siswa,nama_siswa,total_saldo from siswa");
            
            while(res.next()){
                tbl.addRow(new Object[]{
                res.getInt("id"),
                res.getString("id_siswa"),
                res.getString("nama_siswa"),
                res.getString("total_saldo")
                });
            }
        } catch (SQLException e) {
          System.out.println(e);
        }
        }else{
            try {
            Statement st = (Statement) conn.createStatement();
            ResultSet res = st.executeQuery("select id,id_siswa,nama_siswa,total_saldo from siswa where nama_siswa LIKE '%"+cari_nama+"%'");
            
            while(res.next()){
                tbl.addRow(new Object[]{
                res.getInt("id"),
                res.getString("id_siswa"),
                res.getString("nama_siswa"),
                res.getString("total_saldo")
                });
                //jTable2.setModel(tbl);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
        jTable1.setModel(tbl);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jml_penarikan = new javax.swing.JTextField();
        noinduk = new javax.swing.JTextField();
        penarikan_button = new javax.swing.JButton();
        cari_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Penarikan Saldo");

        jLabel2.setText("Jumlah Saldo Penarikan");

        jLabel3.setText("No. Induk Siswa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        penarikan_button.setText("Tarik");
        penarikan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penarikan_buttonActionPerformed(evt);
            }
        });

        cari_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_namaActionPerformed(evt);
            }
        });

        jLabel4.setText("Cari Nama Siswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noinduk, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jml_penarikan, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                        .addGap(24, 24, 24)
                        .addComponent(penarikan_button))
                    .addComponent(cari_nama))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(259, 259, 259))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(noinduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jml_penarikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penarikan_button))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int bar = jTable1.getSelectedRow();
        String namatbl = jTable1.getValueAt(bar, 1).toString();
        noinduk.setText(namatbl);
        //datatable();
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void penarikan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penarikan_buttonActionPerformed
        // TODO add your handling code here:
        int total_setoran_db=0;
        int total=0;
        int penarikan = Integer.parseInt(jml_penarikan.getText());
        int setoran=0;
        int total_penarikan=0;
        try {
            Statement st = (Statement) conn.createStatement();
            ResultSet res = st.executeQuery("select * from siswa where id_siswa='"+noinduk.getText()+"';");
            while(res.next()){
                setoran=res.getInt("total_saldo");
                System.out.println(setoran);
                                
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        System.out.println("penarikan: "+penarikan);
        
        if (penarikan<=setoran){
            try {
            Statement st = (Statement) conn.createStatement();
            ResultSet res = st.executeQuery("select * from siswa where id_siswa='"+noinduk.getText()+"'");
                while(res.next()){
                    total_penarikan=res.getInt("total_penarikan");
                    System.out.println("setoran:"+total_penarikan);
                    System.out.println("jumlah input:"+penarikan);                
                }
            } catch (SQLException e) {
                System.out.println(e);
            }
            
            int ttl_penarikan = total_penarikan+penarikan;
            System.out.println(ttl_penarikan);
                        
            total = setoran-penarikan;
            String sql2 = "UPDATE siswa SET total_saldo='"+total+"' WHERE id_siswa ='"+noinduk.getText()+"'";
            String sql4 = "INSERT INTO penarikan (id_siswa,saldo,tgl) VALUES ('"+noinduk.getText()+"','"+penarikan+"','"+date.getTanggal()+"')";
            String sql5 = "UPDATE siswa SET total_penarikan='"+ttl_penarikan+"' WHERE id_siswa ='"+noinduk.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql2);
                PreparedStatement stat2 = conn.prepareStatement(sql4);
                PreparedStatement stat3 = conn.prepareStatement(sql5);
                stat.executeUpdate();
                stat2.executeUpdate();
                stat3.executeUpdate();
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpam");
            }
            System.out.println("setoran: "+setoran);
            System.out.println("penarikan: "+penarikan);
            System.out.println(total);
            
            }else {
            JOptionPane.showMessageDialog(null, "Maaf, Saldo Tidak Mencukupi");
        }
          
        datatable("");
        noinduk.setText("");
        jml_penarikan.setText("");
        cari_nama.setText("");
    }//GEN-LAST:event_penarikan_buttonActionPerformed

    private void cari_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_namaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari_nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jml_penarikan;
    private javax.swing.JTextField noinduk;
    private javax.swing.JButton penarikan_button;
    // End of variables declaration//GEN-END:variables
}
