/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemrograman.visual;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Aditya Maulana
 */
public class SetoranPanel extends javax.swing.JPanel {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private String id;
    String namatbl;
    /**
     * Creates new form PenarikanPanel
     */
        
      public void datatable(String cari_nama){
       //System.out.println(no_induk);
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("No. Induk");
        tbl.addColumn("Nama");
        tbl.addColumn("Total Saldo");
        if (cari_nama.equals("")){
            try {
            Statement st = (Statement) conn.createStatement();
            ResultSet res = st.executeQuery("select id,id_siswa,nama_siswa,total_saldo from siswa");
            
            while(res.next()){
                tbl.addRow(new Object[]{
                res.getInt("id"),
                res.getString("id_siswa"),
                res.getString("nama_siswa"),
                res.getString("total_saldo")
                });
                //jTable2.setModel(tbl);
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Salah");
        }
        }else{
            try {
            Statement st = (Statement) conn.createStatement();
            //System.out.println(nama);
            //ResultSet res = st.executeQuery("select id,id_siswa,nama_siswa,kelas,alamat,jumlah from siswa INNER JOIN simpanan USING (id_siswa) where nama_siswa LIKE '%"+cari_nama+"%'");
            ResultSet res = st.executeQuery("select id,id_siswa,nama_siswa,total_saldo from siswa where nama_siswa LIKE '%"+cari_nama+"%'");
            
            while(res.next()){
                tbl.addRow(new Object[]{
                res.getInt("id"),
                res.getString("id_siswa"),
                res.getString("nama_siswa"),
                res.getString("total_saldo")
                });
                //jTable2.setModel(tbl);
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "Salah");
        }
    }
        jTable2.setModel(tbl);
    }
        
    
    public SetoranPanel() {
        initComponents();
        
        datatable("");
        cari_nama.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                datatable(cari_nama.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                datatable(cari_nama.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
        nama.setEnabled(false);
    }

      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jml_saldo = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        setor_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cari_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Setoran Saldo");

        jLabel2.setText("Julmah Setoran Saldo");

        jLabel3.setText("No. Induk Siswa");

        jml_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_saldoActionPerformed(evt);
            }
        });

        nama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        setor_button.setText("Setor");
        setor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setor_buttonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Cari Nama Siswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jml_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(setor_button))
                                    .addComponent(cari_nama)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cari_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jml_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setor_button))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jml_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jml_saldoActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int bar = jTable2.getSelectedRow();
        String namatbl = jTable2.getValueAt(bar, 1).toString();
        nama.setText(namatbl);
        datatable("");
    }//GEN-LAST:event_jTable2MouseClicked

    private void setor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setor_buttonActionPerformed
        int total_setoran_db=0;
        int total=0;
        int jmlh = Integer.parseInt(jml_saldo.getText());
        int setoran=0;
        try {
            Statement st = (Statement) conn.createStatement();
            //ResultSet res = st.executeQuery("select sum(jumlah) as hasil from simpanan where id_siswa='"+nama.getText()+"';");
            ResultSet res = st.executeQuery("select * from siswa where id_siswa='"+nama.getText()+"'");
            while(res.next()){
                setoran=res.getInt("total_saldo");
                System.out.println("setoran:"+setoran);
                System.out.println("jumlah input:"+jmlh);                
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        total = setoran+jmlh;
        System.out.println(total);
        
       
        String sql2 = "UPDATE siswa SET total_saldo='"+total+"' WHERE id_siswa ='"+nama.getText()+"'";
        String sql = "INSERT INTO simpanan (id_siswa,jumlah,tgl) VALUES ('"+nama.getText()+"','"+jmlh+"','"+date.getTanggal()+"')";
        try{
            PreparedStatement stat2 = conn.prepareStatement(sql2);
            PreparedStatement stat = conn.prepareStatement(sql);
            stat2.executeUpdate();
            stat.executeUpdate();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpam");
        }
               
        datatable("");
        nama.setText("");
        jml_saldo.setText("");
        cari_nama.setText("");
    }//GEN-LAST:event_setor_buttonActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari_nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jml_saldo;
    private javax.swing.JTextField nama;
    private javax.swing.JButton setor_button;
    // End of variables declaration//GEN-END:variables
}
